### ISSUE TITLE
How to load script when user has consented before?

### ISSUE THREAD

**Issue by dietervb** [DreadfulCode/smallest-cookie-banner#11]
I've got your CookieBanner running with `loadOnConsent` for my Google Analytics script, but I noticed the following issue:

1. User visits page for the first time and sees banner.
2. User consents.
3. The script registered with `loadOnConsent` is loaded.
4. User visits page again, no banner is shown because he/she consented before (the cookie is set)
5. **The registered script is not loaded.** 

I would like to have the analytics script also loaded when the user has consented before.

Thanks in advance for your help!

**Comment by DreadfulCode** [comment]
I was able to replicate and fix this issue with PR https://github.com/DreadfulCode/smallest-cookie-banner/pull/12

The issue was `loadOnConsent` fails to load scripts after accepting with a custom cookie name. (any name other than `cookie_consent`)

Now fixed in v2.1.1
  - npm install smallest-cookie-banner@2.1.1                                                                                                                                                                                                      
  - CDN: https://cdn.jsdelivr.net/npm/smallest-cookie-banner@2.1.1/dist/cookie-banner.min.js

**Comment by dietervb** [comment]
I can confirm that scripts load correctly with `loadOnConsent` when using cookie name `cookie_consent` (default cookie name).

When I use a custom cookie name with v2.1.2, the scripts still do not load on a second visit, with the cookie set.
Only when I specify the cookieName in the `loadOnConsent` method as follows (specified in this [commit]( https://github.com/DreadfulCode/smallest-cookie-banner/commit/de199606872492bb7959ff12a905811146661a3d)):

```
loadOnConsent('analytics', 'script.js', {
  callback: () => console.log('loaded'),
  cookieName: 'my_consent'
});
```
then the scripts do load on a second visit.

FWIW, this is the config I use:
```
      window.CookieBannerConfig = {
          msg: 'Wij gebruiken cookies voor statistieken.',
          acceptText: 'Accepteren',
          rejectText: 'Afwijzen',

          // Behavior
          days: 365,              // Cookie expiry
          forceEU: true,          // Force EU mode (show Accept/Decline everywhere)
          cookieName: 'ck',       // Custom cookie name
          cookieDomain: '.example.com', // For subdomains
          privacyPolicyUrl: '/privacy-policy/',
          "tabs": {
            "enabled": false
          } 
      };
```

**Comment by dietervb** [comment]
I can confirm that the change in PR #13 fixes the issue! 
Thank you.

Will you tag this as release v2.1.3?

**Comment by DreadfulCode** [comment]
Ausgezeichnet!

Issue closed. Here is the release:

https://github.com/DreadfulCode/smallest-cookie-banner/releases/tag/v2.1.3

Thank you @dietervb
